tag_bundles:
  - layout:
      - {
          id: 0,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: -0.113,
          y: 0.122,
          z: 0,
        }
      - {
          id: 2,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0,
          y: 0.122,
          z: 0,
        }
      - {
          id: 3,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.113,
          y: 0.122,
          z: 0,
        }
      - {
          id: 4,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: -0.113,
          y: 0,
          z: 0,
        }
      - {
          id: 5,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.113,
          y: 0,
          z: 0,
        }
      - {
          id: 6,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: -0.113,
          y: -0.122,
          z: 0,
        }
      - {
          id: 7,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0,
          y: -0.122,
          z: 0,
        }
      - {
          id: 8,
          qw: 1.0,
          qx: 0.0,
          qy: 0.0,
          qz: 0.0,
          size: 0.096,
          x: 0.113,
          y: -0.122,
          z: 0,
        }

    name: object_bundle